"""Tests for the NCAAF conference-tier segmentation.

Two targets:
  - evmax.sectors.ncaaf_tiers  — team_tier / matchup_tier / split_event_title
    (the pure classification that segments the CFB soft-market edge thesis).
  - `evmax cleanup shadow clv-tiers ncaaf` — the CLI that buckets resolved CLV
    rows by matchup tier, against a temp fixture DB.

The tier map (evmax/sectors/aliases/ncaaf_tiers.yaml) is generated by
scripts/build_ncaaf_tiers.py from the ESPN FBS scoreboard; these tests assert
against a handful of stable, well-known programs whose conference has not moved.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
from typer.testing import CliRunner

from evmax.cli.commands.shadow import app
from evmax.sectors.ncaaf_tiers import (
    FCS,
    G5,
    P4,
    matchup_tier,
    split_event_title,
    team_tier,
)

runner = CliRunner()


# -------------------------------------------------------------------------
# team_tier — resolves any source spelling through the alias map to a tier
# -------------------------------------------------------------------------


class TestTeamTier:
    @pytest.mark.parametrize(
        "name",
        ["Alabama", "TCU", "TCU Horned Frogs", "North Carolina",
         "Ohio State Buckeyes", "Notre Dame"],
    )
    def test_power4_programs(self, name):
        assert team_tier(name) == P4

    @pytest.mark.parametrize(
        "name",
        ["Toledo", "Toledo Rockets", "Boise State", "James Madison",
         "UConn", "Memphis Tigers"],
    )
    def test_group_of_five_programs(self, name):
        assert team_tier(name) == G5

    @pytest.mark.parametrize("name", ["Idaho State", "Totally Fake U", "", None])
    def test_fcs_and_unknown_are_none(self, name):
        # FCS opponents and unknown strings are intentionally unmapped so buy
        # games fall into the FCS bucket rather than a real tier.
        assert team_tier(name) is None

    def test_notre_dame_independent_is_p4_but_uconn_independent_is_g5(self):
        # Both are FBS Independents (no conference); the split is by marquee.
        assert team_tier("Notre Dame") == P4
        assert team_tier("UConn") == G5


# -------------------------------------------------------------------------
# matchup_tier — combine two sides into the game's tier
# -------------------------------------------------------------------------


class TestMatchupTier:
    def test_both_power4_is_p4(self):
        assert matchup_tier("Alabama", "Georgia") == P4

    def test_both_g5_is_g5(self):
        assert matchup_tier("Toledo", "Memphis") == G5

    def test_one_of_each_is_cross(self):
        assert matchup_tier("Alabama", "Toledo") == "cross"
        assert matchup_tier("Toledo", "Alabama") == "cross"  # order-independent

    def test_any_unmapped_side_is_fcs(self):
        assert matchup_tier("Alabama", "Idaho State") == FCS
        assert matchup_tier("Idaho State", "Toledo") == FCS

    def test_missing_side_is_fcs(self):
        assert matchup_tier(None, "Alabama") == FCS
        assert matchup_tier("Alabama", None) == FCS
        assert matchup_tier(None, None) == FCS


# -------------------------------------------------------------------------
# split_event_title — parse the stored '<A> vs <B>' label
# -------------------------------------------------------------------------


class TestSplitEventTitle:
    def test_vs_separator(self):
        a, b = split_event_title("North Carolina Tar Heels vs TCU Horned Frogs")
        assert a == "North Carolina Tar Heels"
        assert b == "TCU Horned Frogs"

    def test_at_separator_fallback(self):
        assert split_event_title("Toledo at Memphis") == ("Toledo", "Memphis")

    def test_no_separator_returns_none(self):
        assert split_event_title("no separator here") == (None, None)

    def test_empty_returns_none(self):
        assert split_event_title("") == (None, None)
        assert split_event_title(None) == (None, None)


# -------------------------------------------------------------------------
# clv-tiers CLI — buckets resolved CLV rows by matchup tier
# -------------------------------------------------------------------------


def _make_ncaaf_clv_db(tmp_path: Path, rows: list[dict]) -> Path:
    """rows: dicts with market_id, event_title, kalshi_clv_pct, outcome
    (+ optional event_id/mode). Schema is the superset _fetch_clv_rows selects.

    Deliberately no UNIQUE(market_id, scan_date) so get_connection()'s rebuild
    migration (which references columns this minimal fixture omits) is skipped.
    """
    db_path = tmp_path / "predictions.db"
    conn = sqlite3.connect(str(db_path))
    conn.executescript(
        """
        CREATE TABLE ev_predictions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            scan_date TEXT, market_id TEXT, event_id TEXT, event_title TEXT,
            sector TEXT, market_type TEXT, line REAL, model_sources TEXT,
            mode TEXT, kalshi_clv_pct REAL,
            venue TEXT NOT NULL DEFAULT 'kalshi',
            placed INTEGER DEFAULT 0, placed_at TEXT
        );
        CREATE TABLE ev_outcomes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            market_id TEXT UNIQUE, outcome INTEGER
        );
        """
    )
    for r in rows:
        conn.execute(
            """INSERT INTO ev_predictions
               (scan_date, market_id, event_id, event_title, sector, market_type,
                line, model_sources, mode, kalshi_clv_pct)
               VALUES (?,?,?,?,?,?,?,?,?,?)""",
            (
                "2026-09-05",
                r["market_id"],
                r.get("event_id", r["market_id"] + "-evt"),
                r["event_title"],
                "ncaaf",
                "moneyline",
                None,
                "ncaaf_efficiency,elo,sharp",
                r.get("mode", "shadow"),
                r["kalshi_clv_pct"],
            ),
        )
        if r["outcome"] is not None:
            conn.execute(
                "INSERT INTO ev_outcomes (market_id, outcome) VALUES (?, ?)",
                (r["market_id"], r["outcome"]),
            )
    conn.commit()
    conn.close()
    return db_path


@pytest.fixture
def _patch_db(monkeypatch):
    def _apply(db_path):
        from evmax.agents.cleanup import db as db_module

        monkeypatch.setattr(db_module, "DB_PATH", db_path)

    return _apply


class TestClvTiersCommand:
    def test_rejects_non_ncaaf_category(self):
        result = runner.invoke(app, ["clv-tiers", "wnba"])
        assert result.exit_code == 1
        assert "only supports 'ncaaf'" in result.stdout

    def test_empty_db_prints_friendly_message(self, tmp_path, _patch_db):
        _patch_db(_make_ncaaf_clv_db(tmp_path, []))
        result = runner.invoke(app, ["clv-tiers", "ncaaf"])
        assert result.exit_code == 0
        assert "No current-code resolved CLV rows" in result.stdout

    def test_buckets_g5_and_p4_separately(self, tmp_path, _patch_db):
        # G5-vs-G5 games carry +2.00pp CLV; P4-vs-P4 games carry -1.00pp. The
        # command must report each tier's own mean, not a pooled number — the
        # whole point of the soft-market segmentation.
        rows = [
            {"market_id": f"g5_{i}", "event_id": f"g5game{i}",
             "event_title": "Toledo Rockets vs Memphis Tigers",
             "kalshi_clv_pct": 2.0, "outcome": 1}
            for i in range(3)
        ] + [
            {"market_id": f"p4_{i}", "event_id": f"p4game{i}",
             "event_title": "Ohio State Buckeyes vs TCU Horned Frogs",
             "kalshi_clv_pct": -1.0, "outcome": 0}
            for i in range(2)
        ]
        _patch_db(_make_ncaaf_clv_db(tmp_path, rows))
        result = runner.invoke(app, ["clv-tiers", "ncaaf"])
        assert result.exit_code == 0
        out = result.stdout
        # Both tiers present with their own (opposite-signed) means.
        assert "G5" in out and "+2.00pp" in out
        assert "P4" in out and "-1.00pp" in out

    def test_unmapped_side_lands_in_fcs_bucket(self, tmp_path, _patch_db):
        rows = [
            {"market_id": f"buy_{i}", "event_id": f"buygame{i}",
             "event_title": "Alabama Crimson Tide vs Idaho State Bengals",
             "kalshi_clv_pct": 5.0, "outcome": 1}
            for i in range(2)
        ]
        _patch_db(_make_ncaaf_clv_db(tmp_path, rows))
        result = runner.invoke(app, ["clv-tiers", "ncaaf"])
        assert result.exit_code == 0
        # The FCS bucket carries the buy-game rows; real tiers stay empty.
        assert "+5.00pp" in result.stdout
        assert "FCS" in result.stdout
