"""NBA player alias → canonical name mapping."""

# Maps lowercase alias/abbreviation/nickname → canonical "firstname lastname" (lowercase)
NBA_PLAYER_ALIASES: dict[str, str] = {
    # Common abbreviations
    "lbj": "lebron james",
    "lebron": "lebron james",
    "kd": "kevin durant",
    "klay": "klay thompson",
    "steph": "stephen curry",
    "sc30": "stephen curry",
    "pg13": "paul george",
    "pg": "paul george",
    "ad": "anthony davis",
    "cp3": "chris paul",
    "jokic": "nikola jokic",
    "joker": "nikola jokic",
    "giannis": "giannis antetokounmpo",
    "greek freak": "giannis antetokounmpo",
    "tatum": "jayson tatum",
    "jt": "jayson tatum",
    "bam": "bam adebayo",
    "SGA": "shai gilgeous-alexander",
    "sga": "shai gilgeous-alexander",
    "shai": "shai gilgeous-alexander",
    "luka": "luka doncic",
    "luka magic": "luka doncic",
    "dame": "damian lillard",
    "dame time": "damian lillard",
    "ja": "ja morant",
    "devin": "devin booker",
    "book": "devin booker",
    "kt": "karl-anthony towns",
    "kat": "karl-anthony towns",
    "embiid": "joel embiid",
    "jojo": "joel embiid",
    "wemby": "victor wembanyama",
    "victor": "victor wembanyama",
    "cade": "cade cunningham",
    "zion": "zion williamson",
    "lamelo": "lamelo ball",
    "ant": "anthony edwards",
    "ant-man": "anthony edwards",
    "kawhi": "kawhi leonard",
    "klaw": "kawhi leonard",
    "russ": "russell westbrook",
    "brodie": "russell westbrook",
    "melo": "carmelo anthony",
    "KAT": "karl-anthony towns",
    # Full names (common Kalshi spellings)
    "lebron james": "lebron james",
    "stephen curry": "stephen curry",
    "kevin durant": "kevin durant",
    "nikola jokic": "nikola jokic",
    "giannis antetokounmpo": "giannis antetokounmpo",
    "jayson tatum": "jayson tatum",
    "shai gilgeous-alexander": "shai gilgeous-alexander",
    "luka doncic": "luka doncic",
    "damian lillard": "damian lillard",
    "ja morant": "ja morant",
    "joel embiid": "joel embiid",
    "devin booker": "devin booker",
    "anthony edwards": "anthony edwards",
    "victor wembanyama": "victor wembanyama",
    "cade cunningham": "cade cunningham",
    "zion williamson": "zion williamson",
    "lamelo ball": "lamelo ball",
    "kawhi leonard": "kawhi leonard",
    "bam adebayo": "bam adebayo",
    "paul george": "paul george",
    "anthony davis": "anthony davis",
    "karl-anthony towns": "karl-anthony towns",
    "tyrese haliburton": "tyrese haliburton",
    "donovan mitchell": "donovan mitchell",
    "trae young": "trae young",
    "james harden": "james harden",
    "chris paul": "chris paul",
    "draymond green": "draymond green",
    "pascal siakam": "pascal siakam",
    "jalen brunson": "jalen brunson",
    "mikal bridges": "mikal bridges",
    "fred vanvleet": "fred vanvleet",
    "de'aaron fox": "de'aaron fox",
    "brandon ingram": "brandon ingram",
    "darius garland": "darius garland",
    "evan mobley": "evan mobley",
    "jaren jackson jr": "jaren jackson jr",
    "jaren jackson jr.": "jaren jackson jr",
    "scottie barnes": "scottie barnes",
    "josh giddey": "josh giddey",
    "paolo banchero": "paolo banchero",
    "franz wagner": "franz wagner",
    "ivica zubac": "ivica zubac",
    "kristaps porzingis": "kristaps porzingis",
    "kp": "kristaps porzingis",
}
