"""NFL player alias → canonical name mapping."""

# Maps lowercase alias/abbreviation/nickname → canonical "firstname lastname" (lowercase)
NFL_PLAYER_ALIASES: dict[str, str] = {
    # QBs
    "mahomes": "patrick mahomes",
    "pm15": "patrick mahomes",
    "lamar": "lamar jackson",
    "lj8": "lamar jackson",
    "jalen hurts": "jalen hurts",
    "hurts": "jalen hurts",
    "burrow": "joe burrow",
    "joey b": "joe burrow",
    "josh allen": "josh allen",
    "ja17": "josh allen",
    "dak": "dak prescott",
    "prescott": "dak prescott",
    "brock": "brock purdy",
    "purdy": "brock purdy",
    "tua": "tua tagovailoa",
    "tua tagovailoa": "tua tagovailoa",
    "c.j. stroud": "c.j. stroud",
    "cj stroud": "c.j. stroud",
    "stroud": "c.j. stroud",
    "jared goff": "jared goff",
    "goff": "jared goff",
    "kyler": "kyler murray",
    "kyler murray": "kyler murray",
    "trevor lawrence": "trevor lawrence",
    "tj": "trevor lawrence",
    # RBs
    "cmc": "christian mccaffrey",
    "christian mccaffrey": "christian mccaffrey",
    "derrick henry": "derrick henry",
    "king henry": "derrick henry",
    "saquon": "saquon barkley",
    "saquon barkley": "saquon barkley",
    "nick chubb": "nick chubb",
    "breece hall": "breece hall",
    "tony pollard": "tony pollard",
    "de'von achane": "de'von achane",
    "achane": "de'von achane",
    "raheem mostert": "raheem mostert",
    "jahmyr gibbs": "jahmyr gibbs",
    # WRs
    "tyreek": "tyreek hill",
    "cheetah": "tyreek hill",
    "tyreek hill": "tyreek hill",
    "davante adams": "davante adams",
    "stefon diggs": "stefon diggs",
    "justin jefferson": "justin jefferson",
    "jj": "justin jefferson",
    "amon-ra st. brown": "amon-ra st. brown",
    "amon ra": "amon-ra st. brown",
    "deebo": "deebo samuel",
    "deebo samuel": "deebo samuel",
    "ceedee lamb": "ceedee lamb",
    "ceedee": "ceedee lamb",
    "ja'marr chase": "ja'marr chase",
    "jamarr chase": "ja'marr chase",
    "a.j. brown": "a.j. brown",
    "aj brown": "a.j. brown",
    "devonta smith": "devonta smith",
    "puka nacua": "puka nacua",
    "malik nabers": "malik nabers",
    # TEs
    "kelce": "travis kelce",
    "travis kelce": "travis kelce",
    "sam laporta": "sam laporta",
    "mark andrews": "mark andrews",
    "t.j. hockenson": "t.j. hockenson",
    "dallas goedert": "dallas goedert",
    "george kittle": "george kittle",
}
