#!/usr/bin/env python3
"""Build (or refresh) evmax/sectors/aliases/ncaaf_tiers.yaml — a canonical FBS
team → conference-tier (Power-4 vs Group-of-Five) map.

Companion to build_ncaaf_aliases.py. The alias map answers "what is this team's
canonical name?"; this map answers "which market-liquidity tier is it in?". The
CFB edge thesis is that soft, less-watched games (G5 weeknight matchups) carry
more Kalshi-vs-sharp mispricing than efficiently-priced marquee P4 games. That is
an empirical claim the shadow CLV sample has to prove, and this map is the
segmentation key: `evmax cleanup shadow clv-tiers ncaaf` groups resolved ncaaf
CLV rows by matchup tier so P4 / G5 / cross CLV can be compared side by side.

Source of truth is ESPN, exactly like the alias map. We reuse
build_ncaaf_aliases.fetch_season_teams (which returns each FBS team's full ESPN
dict, carrying both ``location`` and ``conferenceId``) and ``_norm_key``, so the
tier map's keys are byte-identical to the alias map's canonical targets — a tier
lookup on any source spelling resolves through the same alias normalization and
lands on the same key. Re-run yearly after realignment:

    python scripts/build_ncaaf_tiers.py            # writes the yaml
    python scripts/build_ncaaf_tiers.py --dry-run  # print, don't write
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_ncaaf_aliases import (  # noqa: E402
    SEASON_WINDOWS,
    _norm_key,
    fetch_season_teams,
)

OUT = (
    Path(__file__).resolve().parents[1]
    / "evmax" / "sectors" / "aliases" / "ncaaf_tiers.yaml"
)

# ESPN conferenceId → tier. Post-realignment "Power 4" = the autobid conferences
# (ACC, Big 12, Big Ten, SEC). Everyone else is Group-of-Five-tier for market-
# liquidity purposes. Pac-12 (9) is the 2025 two-team remnant / 2026 G5-caliber
# rebuild, so it is G5-tier here. FBS Independents (18) are split per team below.
_P4_CONF_IDS = {1, 4, 5, 8}                # ACC, Big 12, Big Ten, SEC
_G5_CONF_IDS = {9, 12, 15, 17, 37, 151}    # Pac-12, CUSA, MAC, Mtn West, Sun Belt, American
_INDEP_CONF_ID = 18

# Independents that trade as marquee (P4-tier) despite carrying no conference.
# Notre Dame is the only current FBS independent with P4-level market attention;
# UConn / UMass / etc. are G5-tier. Keys are canonical (normalized-location).
_INDEP_P4 = {"notre dame"}

_CONF_NAMES = {
    1: "ACC", 4: "Big 12", 5: "Big Ten", 8: "SEC", 9: "Pac-12",
    12: "Conference USA", 15: "MAC", 17: "Mountain West",
    18: "FBS Independents", 37: "Sun Belt", 151: "American",
}


def classify(conf_id: int, canonical: str) -> str | None:
    """P4 / G5 for a known FBS conference id, else None (leave unmapped)."""
    if conf_id in _P4_CONF_IDS:
        return "P4"
    if conf_id in _G5_CONF_IDS:
        return "G5"
    if conf_id == _INDEP_CONF_ID:
        return "P4" if canonical in _INDEP_P4 else "G5"
    return None


def build(season: int) -> dict[str, dict]:
    teams = fetch_season_teams(season)
    out: dict[str, dict] = {}
    skipped: list[tuple[str, object]] = []
    for t in teams.values():
        location = t.get("location") or t.get("shortDisplayName") or ""
        canonical = _norm_key(location)
        cid = t.get("conferenceId")
        if not canonical or cid is None:
            continue
        try:
            cid = int(cid)
        except (TypeError, ValueError):
            continue
        tier = classify(cid, canonical)
        if tier is None:
            skipped.append((canonical, cid))
            continue
        out[canonical] = {"conference": _CONF_NAMES.get(cid, str(cid)), "tier": tier}
    if skipped:
        print(f"  skipped {len(skipped)} unmapped-conf teams: {skipped}", file=sys.stderr)
    return dict(sorted(out.items()))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--season", type=int, default=2025, choices=sorted(SEASON_WINDOWS))
    ap.add_argument("--dry-run", action="store_true", help="Print, do not write.")
    args = ap.parse_args()

    tiers = build(args.season)
    n_p4 = sum(1 for v in tiers.values() if v["tier"] == "P4")
    n_g5 = sum(1 for v in tiers.values() if v["tier"] == "G5")
    print(f"  {len(tiers)} FBS teams: {n_p4} P4, {n_g5} G5", file=sys.stderr)

    import yaml

    header = (
        "# GENERATED by scripts/build_ncaaf_tiers.py — DO NOT edit by hand;\n"
        f"# regenerate after realignment. Source: ESPN {args.season} FBS scoreboard\n"
        "# (groups=80), conferenceId → tier. Keys = NameNormalizer-normalized ESPN\n"
        "# school location, identical to ncaaf.yaml canonical targets. Tier = P4\n"
        "# (ACC/Big 12/Big Ten/SEC + Notre Dame) vs G5 (everyone else). Consumed by\n"
        "# evmax.sectors.ncaaf_tiers → `evmax cleanup shadow clv-tiers ncaaf`.\n"
    )
    text = header + yaml.safe_dump({"tiers": tiers}, sort_keys=True, allow_unicode=True)
    if args.dry_run:
        print(text)
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"  wrote {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
