"""NCAAF (FBS college football) sector handler.

Parallel to the NFL handler — same market shapes (moneyline / spread / total) —
but its own alias namespace (evmax/sectors/aliases/ncaaf.yaml, ~230 FBS + FCS-
opponent schools generated by scripts/build_ncaaf_aliases.py). College football
name reconciliation is much larger and messier than the NFL's 32 fixed franchises
(realignment, FCS opponents, "Miami (OH)" vs "Miami", accented "San José State"),
so the alias map does the heavy lifting; this handler is otherwise stock.
"""

from evmax.models.market import MarketType, PredictionMarket
from evmax.sectors.base import SectorHandler


class NCAAFHandler(SectorHandler):
    name = "ncaaf"
    sharp_source = "pinnacle"

    def enrich_market(self, market: PredictionMarket) -> PredictionMarket:
        """Normalize NCAAF team names via the sector alias map."""
        updates = {}
        if market.team_home:
            updates["team_home"] = self.normalize_team(market.team_home)
        if market.team_away:
            updates["team_away"] = self.normalize_team(market.team_away)
        return market.model_copy(update=updates) if updates else market

    def market_types_supported(self) -> list[str]:
        return [
            MarketType.moneyline,
            MarketType.spread,
            MarketType.total,
        ]
